export const INCIDENT_CATEGORY = {
  PLUMBING: "PLUMBING",
  ELECTRICAL: "ELECTRICAL",
  HVAC: "HVAC",
  APPLIANCES: "APPLIANCES",
  FURNITURE: "FURNITURE",
  LOCKSMITH: "LOCKSMITH",
  CLEANING: "CLEANING",
  OTHER: "OTHER",
};

export const INCIDENT_CATEGORY_LABEL = {
  [INCIDENT_CATEGORY.PLUMBING]: "Fontanería",
  [INCIDENT_CATEGORY.ELECTRICAL]: "Electricidad",
  [INCIDENT_CATEGORY.HVAC]: "Climatización",
  [INCIDENT_CATEGORY.APPLIANCES]: "Electrodomésticos",
  [INCIDENT_CATEGORY.FURNITURE]: "Mobiliario",
  [INCIDENT_CATEGORY.LOCKSMITH]: "Cerrajería",
  [INCIDENT_CATEGORY.CLEANING]: "Limpieza",
  [INCIDENT_CATEGORY.OTHER]: "Otros",
};
